name: base_code_bloc_flutter
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Bloc for state management
  flutter_bloc: ^8.1.6
  # Functional programming things
  dartz: ^0.10.1
  # Value equality
  equatable: ^2.0.5
  # Service locator
  get_it: ^7.7.0
  # Remote API
#  internet_connection_checker: ^1.0.0+1
  http: ^1.2.1
  dio: ^5.4.3+1

  # Local cache
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  go_router: ^14.2.0
  connectivity_plus: ^6.0.3
#  flutter_localization: ^0.2.0
  flutter_localizations:
    sdk: flutter
#  get: ^4.6.6
#  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/lang/en.json
    - assets/lang/ar.json